"""Generate src/game/sdk_symbols.inc for the retail SWROTS XBE.

Inputs:
  - The Cxbx-Reloaded symbol cache for this title (names + addresses of the
    statically linked XDK functions/data, found once by XbSymbolDatabase).
  - The retail default.xbe (MD5 6460ef37862de3af364a0563a0a18c4e), scanned for
    every direct call/jmp from game code into the XDK library sections that the
    port replaces, so calls Cxbx never named still get a trap.

Output: a C++ table of { address, name, kind } consumed by the runtime.

Usage: python tools/gen_symbols.py <symbol_cache.ini> <default.xbe>
"""
import hashlib
import os
import struct
import sys

import capstone

RETAIL_MD5 = "6460ef37862de3af364a0563a0a18c4e"

# XDK library sections that the port replaces with native code. XAPI and the C
# runtime live in .text and keep running as-is.
REPLACED_SECTIONS = {"D3D", "D3DX", "XGRPH", "DSOUND", "WMADEC", "XPP"}

DATA_PREFIXES = ("D3DRS_", "D3D_g_", "g_", "_tls_")
DATA_NAMES = {"XapiThreadNotifyRoutineList", "g_XapiCurrentTopLevelFilter"}


def parse_cache(path):
    syms = {}
    in_symbols = False
    for line in open(path, encoding="latin1"):
        line = line.strip()
        if line.startswith("["):
            in_symbols = line == "[Symbols]"
            continue
        if in_symbols and "=" in line:
            name, addr = (s.strip() for s in line.split("=", 1))
            syms[name] = int(addr, 16)
    return syms


def load_sections(d):
    u32 = lambda o: struct.unpack_from("<I", d, o)[0]
    base = u32(0x104)
    count, table = u32(0x11C), u32(0x120) - base
    secs = []
    for i in range(count):
        flags, va, vsize, raw, rsize, name_addr = struct.unpack_from("<6I", d, table + i * 0x38)
        name = d[name_addr - base:d.index(b"\0", name_addr - base)].decode()
        secs.append((name, va, vsize, raw, rsize))
    return secs


def section_of(secs, addr):
    for name, va, vsize, _, _ in secs:
        if va <= addr < va + vsize:
            return name
    return None


def scan_call_targets(d, secs):
    """Linear-sweep .text and collect direct call/jmp targets in replaced sections."""
    name, va, _, raw, rsize = next(s for s in secs if s[0] == ".text")
    code = d[raw:raw + rsize]
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    targets = set()
    off = 0
    while off < len(code):
        last = None
        for ins in md.disasm(code[off:off + 0x10000], va + off):
            if ins.mnemonic in ("call", "jmp") and ins.op_str.startswith("0x"):
                t = int(ins.op_str, 16)
                if section_of(secs, t) in REPLACED_SECTIONS:
                    targets.add(t)
            last = ins.address + ins.size
        off = off + 1 if last is None else last - va
    return targets


def main():
    cache_path, xbe_path = sys.argv[1], sys.argv[2]
    d = open(xbe_path, "rb").read()
    md5 = hashlib.md5(d).hexdigest()
    if md5 != RETAIL_MD5:
        sys.exit(f"unexpected XBE md5 {md5}")
    secs = load_sections(d)
    syms = parse_cache(cache_path)

    rows = []
    for name, addr in syms.items():
        if name.endswith("_OFFSET") or name.startswith("D3DDevice__m_"):
            continue  # structure offsets, not addresses
        is_data = name.startswith(DATA_PREFIXES) or name in DATA_NAMES
        sec = section_of(secs, addr) or "?"
        kind = "Data" if is_data else ("Sdk" if sec in REPLACED_SECTIONS else "Xapi")
        rows.append((addr, name, kind))

    known = {a for a, _, k in rows if k != "Data"}
    for t in sorted(scan_call_targets(d, secs) - known):
        rows.append((t, f"{section_of(secs, t)}_sub_{t:06X}", "Sdk"))

    rows.sort()
    out = os.path.join(os.path.dirname(__file__), "..", "src", "game", "sdk_symbols.inc")
    with open(out, "w", newline="\n") as f:
        f.write("// Generated by tools/gen_symbols.py -- do not edit.\n")
        f.write(f"// Source XBE md5 {RETAIL_MD5}\n")
        for addr, name, kind in rows:
            f.write(f'SDK_SYMBOL(0x{addr:08X}, "{name}", SymbolKind::{kind})\n')
    print(f"wrote {len(rows)} symbols -> {os.path.normpath(out)}")


if __name__ == "__main__":
    main()
